CREATE DATABASE IF NOT EXISTS db;

USE db;

CREATE TABLE MOTORISTA (
    CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(150),
    CategoriaCNH VARCHAR(2),
    VencimentoCNH DATE,
    FK_VEICULO_placa VARCHAR(7),
    FOREIGN KEY (FK_VEICULO_placa) REFERENCES VEICULO(Placa)
);

CREATE TABLE VEICULO (
    Placa VARCHAR(7) PRIMARY KEY,
    Marca VARCHAR(100),
    Modelo VARCHAR(150),
    Ano YEAR,
    Cor VARCHAR(50),
    FK_MULTA_ID INT,
    FOREIGN KEY (FK_MULTA_ID) REFERENCES MULTA(ID)
);

CREATE TABLE MULTA (
    ID INT PRIMARY KEY,
    Valor DECIMAL(10,2),
    Data DATE,
    PontosPenalidade INT,
    TipoInfracao VARCHAR(200)
);
